- name: Setup Neovim environment
  hosts: local
  become: yes
  tasks:
    - name: Install Neovim
      package:
        name: neovim
        state: present

    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Clone Neovim configuration
      git:
        repo: 'https://github.com/CodeByCalvin/neovimconfig'
        dest: '~/.config/nvim'
        clone: yes
        update: yes
        force: yes

    - name: Install Node.js and npm
      package:
        name:
          - nodejs
          - npm
        state: present


